--[[

             _               _               _   
     /\     (_)             | |             | |  
    /  \     _   _ __ ___   | |__     ___   | |_ 
   / /\ \   | | | '_ ` _ \  | '_ \   / _ \  | __|
  / ____ \  | | | | | | | | | |_) | | (_) | | |_ 
 /_/    \_\ |_| |_| |_| |_| |_.__/   \___/   \__|
                                                 
                                                  

]]--

if not VIP_USER then return end -- VIP only since we use packets everywhere
local version = 0.31

--[[ Skillshot list start ]]--
_G.Champs = {
    ["Aatrox"] = {
        [_Q] = { speed = 450, delay = 0.27, range = 650, minionCollisionWidth = 280},
        [_E] = { speed = 1200, delay = 0.27, range = 1000, minionCollisionWidth = 80}
    },
        ["Ahri"] = {
        [_Q] = { speed = 1670, delay = 0.24, range = 895, minionCollisionWidth = 50},
        [_E] = { speed = 1550, delay = 0.24, range = 920, minionCollisionWidth = 80}
    },
        ["Amumu"] = {
        [_Q] = { speed = 2000, delay = 0.250, range = 1100, minionCollisionWidth = 80}
    },
        ["Anivia"] = {
        [_Q] = { speed = 860.05, delay = 0.250, range = 1100, minionCollisionWidth = 110},
        [_R] = { speed = math.huge, delay = 0.100, range = 615, minionCollisionWidth = 350}
    },
        ["Annie"] = {
        [_W] = { speed = math.huge, delay = 0.25, range = 625, minionCollisionWidth = 0},
        [_R] = { speed = math.huge, delay = 0.2, range = 600, minionCollisionWidth = 0}
    },
        ["Ashe"] = {
        [_W] = { speed = 2000, delay = 0.120, range = 1200, minionCollisionWidth = 85},
        [_R] = { speed = 1600, delay = 0.5, range = 1200, minionCollisionWidth = 0}
    },
        ["Blitzcrank"] = {
        [_Q] = { speed = 1800, delay = 0.250, range = 1050, minionCollisionWidth =  90}
    },
        ["Brand"] = {
        [_Q] = { speed = 1600, delay = 0.625, range = 1100, minionCollisionWidth = 90},
        [_W] = { speed = 900, delay = 0.25, range = 1100, minionCollisionWidth = 0},
    },
        ["Braum"] = {
        [_Q] = { speed = 1600, delay = 225, range = 1000, minionCollisionWidth = 100},
        [_R] = { speed = 1250, delay = 500, range = 1250, minionCollisionWidth = 0},
    },    
        ["Caitlyn"] = {
        [_Q] = { speed = 2200, delay = 0.625, range = 1300, minionCollisionWidth = 0},
        [_E] = { speed = 2000, delay = 0.400, range = 1000, minionCollisionWidth = 80},
    },
        ["Cassiopeia"] = {
        [_Q] = { speed = math.huge, delay = 0.535, range = 850, minionCollisionWidth = 0},
        [_W] = { speed = math.huge, delay = 0.350, range = 850, minionCollisionWidth = 80},
        [_R] = { speed = math.huge, delay = 0.535, range = 850, minionCollisionWidth = 350}
    },
        ["Chogath"] = {
        [_Q] = { speed = 950, delay = 0, range = 950, minionCollisionWidth = 0},
        [_W] = { speed = math.huge, delay = 0.25, range = 700, minionCollisionWidth = 0},
        },
        ["Corki"] = {
        [_Q] = { speed = 1500, delay = 0.350, range = 840, minionCollisionWidth = 0},
        [_R] = { speed = 2000, delay = 0.200, range = 1225, minionCollisionWidth = 60},
    },
        ["Darius"] = {
        [_E] = { speed = 1500, delay = 0.550, range = 530, minionCollisionWidth = 0}
    },
        ["Diana"] = {
        [_Q] = { speed = 2000, delay = 0.250, range = 830, minionCollisionWidth = 0}
    },
        ["DrMundo"] = {
        [_Q] = { speed = 2000, delay = 0.250, range = 1050, minionCollisionWidth = 80}
    },
        ["Draven"] = {
        [_E] = { speed = 1400, delay = 0.250, range = 1100, minionCollisionWidth = 0},
        [_R] = { speed = 2000, delay = 0.5, range = 2500, minionCollisionWidth = 0}
    },
        ["Elise"] = {
        [_E] = { speed = 1450, delay = 0.250, range = 975, minionCollisionWidth = 80}
    },
        ["Ezreal"] = {
        [_Q] = { speed = 2000, delay = 0.251, range = 1200, minionCollisionWidth = 80},
        [_W] = { speed = 1600, delay = 0.25, range = 1050, minionCollisionWidth = 0},
        [_R] = { speed = 2000, delay = 1, range = 20000, minionCollisionWidth = 150}
    },
        ["Fizz"] = {
        [_R] = { speed = 1350, delay = 0.250, range = 1150, minionCollisionWidth = 0}
    },
        ["Galio"] = {
        [_Q] = { speed = 850, delay = 0.25, range = 940, minionCollisionWidth = 0},
        --[_E] = { speed = 2000, delay = 0.400, range = 1180, minionCollisionWidth = 0},
    },
        ["Gragas"] = {
        [_Q] = { speed = 1000, delay = 0.250, range = 1100, minionCollisionWidth = 0}
    },
        ["Graves"] = {
        [_Q] = { speed = 1950, delay = 0.265, range = 950, minionCollisionWidth = 85},
        [_W] = { speed = 1650, delay = 0.300, range = 950, minionCollisionWidth = 0},
        [_R] = { speed = 2100, delay = 0.219, range = 1000, minionCollisionWidth = 30}
    },
        ["Heimerdinger"] = {
                [_W] = { speed = 1200, delay = 0.200, range = 1100, minionCollisionWidth = 70},
                [_E] = { speed = 1000, delay = 0.1, range = 925, minionCollisionWidth = 0},
        },
        ["Irelia"] = {
        [_R] = { speed = 1700, delay = 0.250, range = 1000, minionCollisionWidth = 0}
    },
        ["JarvanIV"] = {
                [_Q] = { speed = 1400, delay = 0.2, range = 800, minionCollisionWidth = 0},
                [_E] = { speed = 200, delay = 0.2, range = 850, minionCollisionWidth = 0},
        },
        ["Jinx"] = {
                [_W] = { speed = 3300, delay = 0.600, range = 1500, minionCollisionWidth = 70},
                [_E] = { speed = 887, delay = 0.500, range = 950, minionCollisionWidth = 0},
                [_R] = { speed = 2500, delay = 0.600, range = 2000 , minionCollisionWidth = 0}
        },
        ["Karma"] = {
        [_Q] = { speed = 1700, delay = 0.250, range = 1050, minionCollisionWidth = 80}
    },
        ["Karthus"] = {
        [_Q] = { speed = 1750, delay = 0.25, range = 875, minionCollisionWidth = 0},
    },
        ["Kennen"] = {
        [_Q] = { speed = 1700, delay = 0.180, range = 1050, minionCollisionWidth = 70}
    },
        ["Khazix"] = {
        [_W] = { speed = 828.5, delay = 0.225, range = 1000, minionCollisionWidth = 100}
    },
        ["KogMaw"] = {
        [_R] = { speed = 1050, delay = 0.250, range = 2200, minionCollisionWidth = 0}
    },
        ["Leblanc"] = {
        [_E] = { speed = 1600, delay = 0.250, range = 960, minionCollisionWidth = 0},
        [_R] = { speed = 1600, delay = 0.250, range = 960, minionCollisionWidth = 0},
    },
        ["LeeSin"] = {
        [_Q] = { speed = 1800, delay = 0.250, range = 1100, minionCollisionWidth = 100}
    },
        ["Leona"] = {
        [_E] = { speed = 2000, delay = 0.250, range = 900, minionCollisionWidth = 0},
        [_R] = { speed = 2000, delay = 0.250, range = 1200, minionCollisionWidth = 0},
    },
        ["Lissandra"] = {
        [_Q] = { speed = 1800, delay = 0.250, range = 725, minionCollisionWidth = 00}
    },
        ["Lucian"] = {
        [_W] = { speed = 1470, delay = 0.288, range = 1000, minionCollisionWidth = 25}
    },
        ["Lulu"] = {
        [_Q] = { speed = 1530, delay = 0.250, range = 945, minionCollisionWidth = 80}
    },
        ["Lux"] = {
        [_Q] = { speed = 1200, delay = 0.245, range = 1300, minionCollisionWidth = 50},
        [_E] = { speed = 1400, delay = 0.245, range = 1100, minionCollisionWidth = 0},
        [_R] = { speed = math.huge, delay = 0.245, range = 3500, minionCollisionWidth = 0}
    },
        ["Malzahar"] = {
        [_Q] = { speed = 1170, delay = 0.600, range = 900, minionCollisionWidth = 50}
    },
        ["Mordekaiser"] = {
        [_E] = { speed = math.huge, delay = 0.25, range = 700, minionCollisionWidth = 0},
        },
        ["Morgana"] = {
        [_Q] = { speed = 1200, delay = 0.250, range = 1300, minionCollisionWidth = 80}
    },
        ["Nami"] = {
        [_Q] = { speed = math.huge, delay = 0.8, range = 850, minionCollisionWidth = 0}
    },
        ["Nautilus"] = {
        [_Q] = { speed = 2000, delay = 0.250, range = 1080, minionCollisionWidth = 100}
    },
        ["Nidalee"] = {
        [_Q] = { speed = 1300, delay = 0.125, range = 1500, minionCollisionWidth = 60},
    },
        ["Nocturne"] = {
        [_Q] = { speed = 1600, delay = 0.250, range = 1200, minionCollisionWidth = 0}
    },
        ["Olaf"] = {
        [_Q] = { speed = 1600, delay = 0.25, range = 1000, minionCollisionWidth = 0}
    },
        ["Quinn"] = {
        [_Q] = { speed = 1600, delay = 0.25, range = 1050, minionCollisionWidth = 100}
    },
        ["Rumble"] = {
        [_E] = { speed = 2000, delay = 0.250, range = 950, minionCollisionWidth = 80}
    },
        ["Sejuani"] = {
        [_R] = { speed = 1300, delay = 0.200, range = 1175, minionCollisionWidth = 0}
    },
        ["Sivir"] = {
        [_Q] = { speed = 1330, delay = 0.250, range = 1075, minionCollisionWidth = 0}
    },
        ["Skarner"] = {
        [_E] = { speed = 1200, delay = 0.250, range = 760, minionCollisionWidth = 0}
    },
        ["Swain"] = {
        [_Q] = { speed = math.huge, delay = 0.500, range = 900, minionCollisionWidth = 0}
    },
        ["Syndra"] = {
        [_Q] = { speed = math.huge, delay = 0.400, range = 800, minionCollisionWidth = 0}
    },
        ["Thresh"] = {
        [_Q] = { speed = 1900, delay = 0.500, range = 1075, minionCollisionWidth = 80}
    },
        ["Twitch"] = {
        [_W] = {speed = 1750, delay = 0.283, range = 900, minionCollisionWidth = 0}
    },
        ["TwistedFate"] = {
        [_Q] = { speed = 1450, delay = 0.200, range = 1450, minionCollisionWidth = 0}
    },
        ["Urgot"] = {
        [_Q] = { speed = 1600, delay = 0.175, range = 1000, minionCollisionWidth = 100},
        [_E] = { speed = 1750, delay = 0.25, range = 900, minionCollisionWidth = 0}
    },
        ["Varus"] = {
       --[_Q] = { speed = 1850, delay = 0.1, range = 1475, minionCollisionWidth = 0},
        [_E] = { speed = 1500, delay = 0.245, range = 925, minionCollisionWidth = 0},
        [_R] = { speed = 1950, delay = 0.5, range = 1075, minionCollisionWidth = 0}
    },
        ["Veigar"] = {
        [_W] = { speed = 900, delay = 0.25, range = 900, minionCollisionWidth = 0}
    },
        ["Viktor"] = {
                [_W] = { speed = math.huge, delay = 0.25, range = 625, minionCollisionWidth = 0},
                [_E] = { speed = 1200, delay = 0.25, range = 1225, minionCollisionWidth = 0},
                [_R] = { speed = 1000, delay = 0.25, range = 700, minionCollisionWidth = 0},
    },
        ["Velkoz"] = {
                [_Q] = { speed = 1300, delay = 0.066, range = 1100, minionCollisionWidth = 50},
                [_W] = { speed = 1700, delay = 0.064, range = 1050, minionCollisionWidth = 0},
                [_E] = { speed = 1500, delay = 0.333, range = 1100, minionCollisionWidth = 0},
    },    
        ["Xerath"] = {
        [_Q] = { speed = 3000, delay = 0.6, range = 1100, minionCollisionWidth = 0},
        [_R] = { speed = 2000, delay = 0.25, range = 1100, minionCollisionWidth = 0}
    },
        ["Yasuo"] = {
        [_Q] =  { speed = math.huge, delay = 250, range = 475, minionCollisionWidth = 0},
    },
        ["Zed"] = {
        [_Q] = { speed = 1700, delay = 0.2, range = 925, minionCollisionWidth = 0},
    },
        ["Ziggs"] = {
        [_Q] = { speed = 1722, delay = 0.218, range = 850, minionCollisionWidth = 0},
                [_W] = { speed = 1727, delay = 0.249, range = 1000, minionCollisionWidth = 0},
                [_E] = { speed = 2694, delay = 0.125, range = 900, minionCollisionWidth = 0},
                [_R] = { speed = 1856, delay = 0.1014, range = 2500, minionCollisionWidth = 0},
    },
        ["Zyra"] = {
                 [_Q] = { speed = math.huge, delay = 0.7, range = 800, minionCollisionWidth = 0},
         [_E] = { speed = 1150, delay = 0.16, range = 1100, minionCollisionWidth = 0}
    }
}
--[[ Skillshot list end ]]--

assert(load(Base64Decode("G0x1YVIAAQQEBAgAGZMNChoKAAAAAAAAAAAAARa0AAAAAwCAAEEAAACBQAAAwYAAAAbBQAAHAUECQUEBAIGBAQAdgYABlgABAcbAQQABAQIA1gCBAQFBAgBAAYAAgAEAARaBAQJlAQAAGwAAABfADICGgUIAwAGAAAHCAgCdgYABmwEAABeACoDGQUMABoJDAEACAAMdAgAB3YEAABjAwwMXAAGAxoFDAAACAAPdgQAB20EAABcAAIDEAQAACMABhsYBQwDbAQAAFwAHgMaBQwAGAkQA3YEAAQYCQwAZAIIDFwADgMABgAIBQgQARgJDABZCAgTdQQABwAGAAgGCBADdQQABxsFEACVCAABBAgUA3UGAARdAAoDAAYACAUIFAEYCQwCBggUAFoICBN1BAAEXgACAwAGAAgHCBQDdQQABhgFGAMZBRgABggYA1gGCA52BAAGbAQAAF0ABgIbBRgDBAQcAnUEAAYYBRwCdgYAACICBjoaBRwCbAQAAF4ACgIYBRgDGQUYAAcIHANYBggOdgQABmwEAABfAAICGwUYAwQEIAJ1BAAEIgMiQhoFHAJsBAAAXwASAhgFGAMZBRgABwggA1gGCA52BAAGbAQAAFwADgIYBRgDGQUYAAQIJANYBggOdgQABmwEAABdAAYCGwUYAwUEJAJ1BAAGGQUkAnYGAAAiAAZOGwUkAxgFKAMdBygOHwQEDm0EAABcAAIAfAIAAhoFKAJ1BgACGwUkAxgFKAMdBygOHwQEDxAEAAgbDSgBGA0sAgUMLAMaDSwADBIAAHYOAAksDAQCGw0sASgNMB4ZDTABKg0wHhsNMAEoDTQeGQ00ASoNNB4bDTQDLAwAACwQAAkMEAACDBAAAwwQAAAMFAAAkRAACSwQAAoMEAADDBAAAAwUAAEMFAABkRAACpYQAAAiABJylxAAACICEnKUEAQAIgASdpUQBAAiAhJ2lhAEACIAEnqXEAQAIgISepQQCAAiABJ8fAIAAPwAAAAQPAAAAcmF3LmdpdGh1Yi5jb20ABCYAAAAvbmViZWx3b2xmaS9zY3JpcHRzL21hc3Rlci9BaW1ib3QubHVhAAQHAAAAP3JhbmQ9AAQFAAAAbWF0aAAEBwAAAHJhbmRvbQADAAAAAAAA8D8DAAAAAACIw0AEDAAAAFNDUklQVF9QQVRIAAQLAAAAQWltYm90Lmx1YQAECQAAAGh0dHBzOi8vAAQNAAAAR2V0V2ViUmVzdWx0AAQqAAAAL25lYmVsd29sZmkvc2NyaXB0cy9tYXN0ZXIvQWltYm90LnZlcnNpb24ABA4AAABTZXJ2ZXJWZXJzaW9uAAQFAAAAdHlwZQAECQAAAHRvbnVtYmVyAAQHAAAAbnVtYmVyAAQIAAAAdmVyc2lvbgAEGAAAAE5ldyB2ZXJzaW9uIGF2YWlsYWJsZSB2AAQgAAAAVXBkYXRpbmcsIHBsZWFzZSBkb24ndCBwcmVzcyBGOQAEDAAAAERlbGF5QWN0aW9uAAMAAAAAAAAIQAQdAAAATG9hZGVkIHRoZSBsYXRlc3QgdmVyc2lvbiAodgAEAgAAACkABB8AAABFcnJvciBkb3dubG9hZGluZyB2ZXJzaW9uIGluZm8ABAoAAABGaWxlRXhpc3QABAkAAABMSUJfUEFUSAAEEQAAAC9WUHJlZGljdGlvbi5sdWEABAgAAAByZXF1aXJlAAQMAAAAVlByZWRpY3Rpb24ABAMAAABWUAAECQAAAFZJUF9VU0VSAAQQAAAAL1Byb2RpY3Rpb24ubHVhAAQLAAAAUHJvZGljdGlvbgAECwAAAHByb2RzdGF0dXMAAQEEDwAAAERpdmluZVByZWQubHVhAAQQAAAARGl2aW5lUHJlZC5sdWFjAAQLAAAARGl2aW5lUHJlZAAEAwAAAERQAAQHAAAAQ2hhbXBzAAQHAAAAbXlIZXJvAAQJAAAAY2hhck5hbWUABAwAAABIb29rUGFja2V0cwAEDwAAAFRhcmdldFNlbGVjdG9yAAQSAAAAVEFSR0VUX05FQVJfTU9VU0UAAwAAAAAAcJdABA0AAABEQU1BR0VfTUFHSUMABAMAAABfUQAEAgAAAFEABAMAAABfVwAEAgAAAFcABAMAAABfRQAEAgAAAEUABAMAAABfUgAEAgAAAFIABBcAAABTQ1JJUFRfUEFSQU1fT05LRVlET1dOAAQHAAAAT25Mb2FkAAQHAAAAT25UaWNrAAQJAAAAT25XbmRNc2cABAwAAABJc1ZlaWdhckx1eAAEDQAAAE9uU2VuZFBhY2tldAAEEAAAAEdldEN1c3RvbVRhcmdldAAECwAAAENDYXN0U3BlbGwACQAAAAMAAAAFAAAAAQAFBwAAAEYAQACBQAAAwAAAAAGBAACWAAEBXUAAAR8AgAADAAAABAYAAABwcmludAAEQwAAADxmb250IGNvbG9yPSIjNjY5OWZmIj48Yj5BaW1ib3Q6PC9iPjwvZm9udD4gPGZvbnQgY29sb3I9IiNGRkZGRkYiPgAECQAAAC48L2ZvbnQ+AAAAAAABAAAAAAAQAAAAQG9iZnVzY2F0ZWQubHVhAAcAAAAEAAAABQAAAAUAAAAFAAAABQAAAAQAAAAFAAAAAQAAAAQAAABiYmEAAAAAAAcAAAABAAAABQAAAF9FTlYADgAAABIAAAAAAAQGAAAABgBAAEUAgACFAAAB5QAAAB1AAAIfAIAAAQAAAAQNAAAARG93bmxvYWRGaWxlAAEAAAAPAAAAEgAAAAAABgkAAAAFAAAAQQAAAIZAwADBgAAABsHAAEEBAQBWQIEAHUAAAR8AgAAFAAAABBgAAABTdWNjZXNzZnVsbHkgdXBkYXRlZC4gKAAECAAAAHZlcnNpb24ABAUAAAAgPT4gAAQOAAAAU2VydmVyVmVyc2lvbgAELwAAACksIHByZXNzIEY5IHR3aWNlIHRvIGxvYWQgdGhlIHVwZGF0ZWQgdmVyc2lvbi4AAAAAAAIAAAAAAwAAEAAAAEBvYmZ1c2NhdGVkLmx1YQAJAAAAEAAAABEAAAARAAAAEgAAABIAAAASAAAAEgAAABAAAAASAAAAAAAAAAIAAAADAAAAZGQABQAAAF9FTlYABAAAAAAAAQQBAwEFEAAAAEBvYmZ1c2NhdGVkLmx1YQAGAAAADwAAAA8AAAAPAAAAEgAAAA8AAAASAAAAAAAAAAQAAAAFAAAAX0VOVgADAAAAY2QAAwAAAGJkAAMAAABkZAAfAAAAMgAAAAAADqgAAAAGQEAAQYAAAIbAQABWgIAAgYAAAMbAQACWwAABHYCAAQgAAIAGAEAADABBAIFAAQDBgAEAHUAAAgYAQAAHgEEADMBBAIEAAgDBQAIABoFCAEMBAAAdQAADBgBAAAeAQQAMwEEAgcACAMEAAwAGQUMAQYEDAB1AAAMGAEAAB4BBAAzAQQCBwAMAwQAEAAZBRABBgQQAgcEEAMEBBQABwgQAHUCABAYAQAAHgEEADMBBAIHAAgDBAAMABkFDAEGBAwAdQAADCwCAAUGAAwCBgAMAwYADACRAgAFGQEUAhoBFAMHABQCWwAABXYAAAVsAAAAXAACACkBGjEaARgBbAAAAF4AEgEZARQCGgEUAwcAGAJbAAAFdgAABWwAAABfAAYBGQEUAhoBFAMEABwCWwAABXYAAAVsAAAAXAACACkBHikaARwBbAAAAFwAAgArAR4lLAIABgYADAMGAAwABgQMAZECAARhAAAAXwACARgBIAIFACABdQAABHwCAAEYAQABHgMEATMDBAMGACAABwQgARgFJAIEBBgDAAQAAXUCAA0YAQABMAMEAwUAJAAGBCQBdQAACRsBJAIUAgABdAAEBF0AFgIYBQACHgUkDjMFBAwYCAQFBggMAhQKAAcMCAAAGA0oAB0NKBkYDAQEdAwABnUEAAIYBAQHLAYACB4LKAkfCygKHAssCx0LLAgADAALkQYACCMEBA0iBSwJigAAA48D5f0YAQABMwMsAxQAAA11AgAFGAEAATMDBAMEADAABQQwARoFMAIMBgADGAUoAx0HKAwHCDADdAQABXUAAAEYAQABMwMEAwQANAAFBDQBGQUQAgcEEAMHBBAABgg0AQcIEAF1AgARGAEAATMDNAMEADABdQIABiEFOnB8AgAA6AAAABAcAAABDb25maWcABA0AAABzY3JpcHRDb25maWcABAkAAABBaW1ib3QgdgAECAAAAHZlcnNpb24ABAsAAABhZGRTdWJNZW51AAQXAAAAW1ByZWRpY3Rpb25dOiBTZXR0aW5ncwAECQAAAHByQ29uZmlnAAQJAAAAYWRkUGFyYW0ABAMAAABwYwAEGwAAAFVzZSBQYWNrZXRzIFRvIENhc3QgU3BlbGxzAAQTAAAAU0NSSVBUX1BBUkFNX09OT0ZGAAQEAAAAcXFxAAQ5AAAALS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0ABBIAAABTQ1JJUFRfUEFSQU1fSU5GTwAEAQAAAAAECgAAAGhpdGNoYW5jZQAECQAAAEFjY3VyYWN5AAQTAAAAU0NSSVBUX1BBUkFNX1NMSUNFAAMAAAAAAAAAQAMAAAAAAAAAAAMAAAAAAAAIQAQKAAAARmlsZUV4aXN0AAQJAAAATElCX1BBVEgABBAAAABWUHJlZGljdGlvbi5sdWEAAwAAAAAAAPA/BAwAAABWUHJlZGljdGlvbgAECQAAAFZJUF9VU0VSAAQPAAAARGl2aW5lUHJlZC5sdWEABBAAAABEaXZpbmVQcmVkLmx1YWMABAsAAABEaXZpbmVQcmVkAAQLAAAAcHJvZHN0YXR1cwAECwAAAFByb2RpY3Rpb24ABAoAAABQcmludENoYXQABB4AAABQTEVBU0UgRE9XTkxPQUQgQSBQUkVESUNUSU9OIQAEBAAAAHBybwAEEwAAAFR5cGUgb2YgcHJlZGljdGlvbgAEEgAAAFNDUklQVF9QQVJBTV9MSVNUAAQRAAAAU3VwcG9ydGVkIHNraWxscwAECQAAAHNrQ29uZmlnAAQGAAAAcGFpcnMABAcAAABzdHJpbmcABAUAAABieXRlAAQGAAAAcmFuZ2UABAYAAABzcGVlZAAEBgAAAGRlbGF5AAQGAAAAd2lkdGgAAQEEBgAAAGFkZFRTAAQEAAAAdG9nAAQOAAAAQWltYm90IG9uL29mZgAEGQAAAFNDUklQVF9QQVJBTV9PTktFWVRPR0dMRQAEAgAAAFQABAwAAAByYW5nZW9mZnNldAAEFgAAAFJhbmdlIERlY3JlYXNlIE9mZnNldAADAAAAAAAAaUAECgAAAHBlcm1hU2hvdwAEBQAAAG5hbWUABAcAAABUYXJnZXQAAAAAAAcAAAAAAAEGAQ0BDgEPAREBDBAAAABAb2JmdXNjYXRlZC5sdWEAqAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACEAAAAhAAAAIQAAACEAAAAhAAAAIgAAACIAAAAiAAAAIgAAACIAAAAiAAAAIgAAACIAAAAjAAAAIwAAACMAAAAjAAAAIwAAACMAAAAjAAAAIwAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJQAAACUAAAAlAAAAJQAAACUAAAAlAAAAJQAAACUAAAAlAAAAJQAAACUAAAAlAAAAJQAAACUAAAAlAAAAJQAAACUAAAAlAAAAJQAAACUAAAAmAAAAJwAAACcAAAAnAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAArAAAAKwAAACsAAAArAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAuAAAALgAAAC4AAAAuAAAALwAAAC8AAAAvAAAALwAAAC8AAAAvAAAALwAAAC8AAAAvAAAALwAAAC8AAAAvAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAAC4AAAAuAAAAMAAAADAAAAAwAAAAMAAAADEAAAAxAAAAMQAAADEAAAAxAAAAMQAAADEAAAAxAAAAMQAAADEAAAAxAAAAMgAAADIAAAAyAAAAMgAAADIAAAAyAAAAMgAAADIAAAAyAAAAMgAAADIAAAAyAAAAMgAAADIAAAAyAAAAMgAAAAYAAAAEAAAAYmJhADYAAACoAAAAEAAAAChmb3IgZ2VuZXJhdG9yKQBwAAAAiQAAAAwAAAAoZm9yIHN0YXRlKQBwAAAAiQAAAA4AAAAoZm9yIGNvbnRyb2wpAHAAAACJAAAABAAAAGNiYQBxAAAAhwAAAAQAAABkYmEAcQAAAIcAAAAHAAAABQAAAF9FTlYABAAAAF9fYQAEAAAAYmFhAAQAAABjYWEABAAAAGRhYQAEAAAAYWJhAAQAAABhYWEAMwAAAFIAAAAAAA4XAQAABgBAAAdAQAAbAAAAF0BEgAaAQAAdgIAACQCAAAUAgAAYwEAAFwAAgB8AgAAGAEEARQAAAR0AAQEXAEGARsGAARhAwQIXQECARoFBAEzBwQLAAYABXYGAAVsBAAAXwD6ARgFAAEcBwgJHQcICGIDCAhdAHYBHwUICGADDAhfABYBHQUMCWwEAABdAAoBGgUMATMHDAsUBgAAHAkQCR0JEAoeCRALHwkQCBoNBAF0BAQQXwA+ARoFDAEwBxQLFAYAABwJEAkdCRAKHgkQCx8JEAgaDQQBHQ0UCXQGBBBcADYBHwUICGIDFAhfABYBHQUMCWwEAABdAAoBGgUMATMHFAsUBgAAHAkQCR0JEAoeCRALHwkQCBoNBAF0BAQQXAAmARoFDAEwBxgLFAYAABwJEAkdCRAKHgkQCx8JEAgaDQQBHQ0UCXQGBBBdABoBHwUICGEDGAheABYBHQUMCWwEAABdAAoBGgUMATIHGAsUBgAAHAkQCR0JEAoeCRALHwkQCBoNBAF0BAQQXQAKARoFDAEwBxQLFAYAABwJEAkdCRAKHgkQCx8JEAgaDQQBHQ0UCXQGBBEbBRgCGAUAAhwFCA4cBRwMaQAEDF8ABgEZBRwCAAYABxoFHAMfBxwMGgkcABwJIBF1BAAIXQAWARsFGAIYBQACHAUIDhwFHA46BQgMaQAEDF8ABgEZBRwCAAYABxoFHAMfBxwMGgkcABwJIBF1BAAIXgAGARkFHAIABgAHGQUgAx8HHAwZCSAAHAkgEXUEAAsiAyAEXACCARgFAAEcBwgJHQcICGMDIAhfACIBGAUkAWwEAABcACIBGQUkAWwEAABdAB4BGgUkAR8HJAoUBgADHgUQCB8JEAkcCRAKHQkQCxoJBAF3BgANYwMACF0ACgMcBSgPdgYAA20EAABdAAYDGQUcAAAKAAUfCxwKHAsgC3UEAAheAAYDGQUcAAAKAAUZCSABHwscEhkJIAIcCSAXdQQACyIDIARfAFYBGAUAARwHCAkdBwgIYQMoCF4AUgEYBSQBbAQAAF8ATgEaBSgCFAYAAXYEAAYdBRQKbAQAAF4AAgIHBCgCbQQAAF0AAgIYBSwCHQUsDxoFLAAACgAHdgQAB2wEAABcAAICBgQIAx8FCAhgAwwMXQAKAxgFMAAfCRAJHgkQCh0JEAscCRALPQswFAAMAA92BAAMIwIGXFwAGgMfBQgIYgMUDF0ACgMaBTAAHwkQCR4JEAodCRALHAkQCz0LMBQADAAPdgQADCMCBlxfAAoDHwUICGEDGAxcAAoDGwUwAB8JEAkeCRAKHQkQCxwJEAs9CzAUAAwAD3YEAAwjAgZfGAU0AzEHNA0ACgAKGwksAwcIIAN0BgQKGgk0Ah8JNBYcCTgUYgIIDF0ABgIZCRwDAAoABB8NHBEcDSASdQgACF4ABgIZCRwDAAoABBkNIAAfDRwZGQ0gARwPIBp1CAALIgMgBIoAAAKMAvn8fAIAAOQAAAAQHAAAAQ29uZmlnAAQEAAAAdG9nAAQQAAAAR2V0Q3VzdG9tVGFyZ2V0AAAEBgAAAHBhaXJzAAEBBAcAAABteUhlcm8ABAwAAABDYW5Vc2VTcGVsbAAECQAAAHByQ29uZmlnAAQEAAAAcHJvAAMAAAAAAADwPwQFAAAAdHlwZQAEBwAAAGxpbmVhcgAEBAAAAGFvZQAEAwAAAFZQAAQXAAAAR2V0TGluZUFPRUNhc3RQb3NpdGlvbgAEBgAAAGRlbGF5AAQGAAAAd2lkdGgABAYAAAByYW5nZQAEBgAAAHNwZWVkAAQUAAAAR2V0TGluZUNhc3RQb3NpdGlvbgAECgAAAGNvbGxpc2lvbgAECQAAAGNpcmN1bGFyAAQbAAAAR2V0Q2lyY3VsYXJBT0VDYXN0UG9zaXRpb24ABBgAAABHZXRDaXJjdWxhckNhc3RQb3NpdGlvbgAEBQAAAGNvbmUABBcAAABHZXRDb25lQU9FQ2FzdFBvc2l0aW9uAAQKAAAASGl0Q2hhbmNlAAQKAAAAaGl0Y2hhbmNlAAQLAAAAQ0Nhc3RTcGVsbAAEDQAAAENhc3RQb3NpdGlvbgAEAgAAAHgABAIAAAB6AAQJAAAAbW91c2VQb3MAAQADAAAAAAAAAEAECQAAAFZJUF9VU0VSAAQLAAAAcHJvZHN0YXR1cwAECwAAAFByb2RpY3Rpb24ABA4AAABHZXRQcmVkaWN0aW9uAAQLAAAAbUNvbGxpc2lvbgADAAAAAAAACEAECQAAAERQVGFyZ2V0AAMAAAAAAAAAAAQFAAAAbWF0aAAEBQAAAGh1Z2UABAwAAABJc1ZlaWdhckx1eAAEBgAAAFNwZWxsAAQHAAAATGluZVNTAAMAAAAAAECPQAQJAAAAQ2lyY2xlU1MABAcAAABDb25lU1MABAMAAABEUAAECAAAAHByZWRpY3QABAoAAABTa2lsbFNob3QABAcAAABTVEFUVVMABAwAAABTVUNDRVNTX0hJVAAAAAAABAAAAAAAAQsBBgEQEAAAAEBvYmZ1c2NhdGVkLmx1YQAXAQAANAAAADQAAAA0AAAANAAAADQAAAA0AAAANAAAADQAAAA0AAAANAAAADQAAAA1AAAANQAAADUAAAA1AAAANwAAADcAAAA3AAAANwAAADcAAAA3AAAANwAAADcAAAA3AAAAOQAAADkAAAA5AAAAOQAAADkAAAA6AAAAOgAAADoAAAA7AAAAOwAAADsAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPQAAAD0AAAA9AAAAPQAAAD0AAAA9AAAAPQAAAD0AAAA9AAAAPQAAAD0AAAA9AAAAPQAAAD0AAAA+AAAAPgAAAD4AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABBAAAAQQAAAEEAAABCAAAAQgAAAEIAAABCAAAAQgAAAEIAAABCAAAAQgAAAEIAAABCAAAAQwAAAEMAAABDAAAAQwAAAEMAAABDAAAAQwAAAEMAAABDAAAAQwAAAEQAAABEAAAARAAAAEQAAABEAAAARAAAAEUAAABFAAAARQAAAEUAAABFAAAARQAAAEUAAABFAAAARQAAAEUAAABFAAAARQAAAEUAAABFAAAARQAAAEYAAABGAAAARgAAAEYAAABGAAAARgAAAEYAAABGAAAARgAAAEYAAABGAAAARgAAAEYAAABGAAAARgAAAEYAAABGAAAARwAAAEcAAABHAAAARwAAAEcAAABHAAAARwAAAEcAAABHAAAARwAAAEcAAABIAAAASAAAAEgAAABIAAAASAAAAEgAAABIAAAASAAAAEgAAABJAAAASQAAAEkAAABJAAAASQAAAEkAAABKAAAASgAAAEoAAABKAAAASgAAAEoAAABKAAAASgAAAEoAAABKAAAASgAAAEoAAABKAAAASgAAAEoAAABKAAAASgAAAEoAAABKAAAASgAAAEoAAABKAAAASgAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAASwAAAEsAAABLAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATQAAAE0AAABNAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE4AAABOAAAATgAAAE8AAABPAAAATwAAAE8AAABPAAAATwAAAE8AAABPAAAATwAAAE8AAABPAAAATwAAAE8AAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABRAAAAUQAAAFEAAABRAAAAUQAAAFEAAABRAAAAUQAAAFEAAABRAAAAUQAAAFIAAABSAAAAUgAAAFIAAABSAAAAUgAAAFIAAABSAAAANQAAADUAAABSAAAAHgAAABAAAAAoZm9yIGdlbmVyYXRvcikADgAAABYBAAAMAAAAKGZvciBzdGF0ZSkADgAAABYBAAAOAAAAKGZvciBjb250cm9sKQAOAAAAFgEAAAQAAABiYmEADwAAABQBAAAEAAAAY2JhAA8AAAAUAQAABAAAAGRiYQAsAAAALAAAAAQAAABfY2EALAAAACwAAAAEAAAAYWNhACwAAAAsAAAABAAAAGRiYQA3AAAANwAAAAQAAABfY2EANwAAADcAAAAEAAAAYWNhADcAAAA3AAAABAAAAGRiYQBHAAAARwAAAAQAAABfY2EARwAAAEcAAAAEAAAAYWNhAEcAAABHAAAABAAAAGRiYQBSAAAAUgAAAAQAAABfY2EAUgAAAFIAAAAEAAAAYWNhAFIAAABSAAAABAAAAGRiYQBiAAAAYgAAAAQAAABfY2EAYgAAAGIAAAAEAAAAYWNhAGIAAABiAAAABAAAAGRiYQBtAAAAbQAAAAQAAABfY2EAbQAAAG0AAAAEAAAAYWNhAG0AAABtAAAABAAAAGRiYQCnAAAAuwAAAAQAAABfY2EApwAAALsAAAAEAAAAZGJhAMcAAAAUAQAABAAAAF9jYQDPAAAAFAEAAAQAAABhY2EAAQEAABQBAAAEAAAAYmNhAAEBAAAUAQAABAAAAGNjYQABAQAAFAEAAAQAAAAFAAAAX0VOVgAEAAAAX2FhAAQAAABfX2EABAAAAF9iYQBTAAAAWAAAAAIABDQAAACGAEAAGIAAABdAAoCGQEAAwYAAAJ2AAAEYgIAAFwABgIbAwACbAAAAF0AAgIgAwYEXQAmAhgBAABiAAAAXQAKAhkBAAMFAAQCdgAABGICAABcAAYCGgMEAmwAAABdAAICIAEGDFwAGgIYAQAAYgAAAF0ACgIZAQADBwAEAnYAAARiAgAAXAAGAhgDCAJsAAAAXQACAiABBhBfAAoCGAEAAGIAAABcAAoCGQEAAwUACAJ2AAAEYgIAAF8AAgIaAwgCbAAAAFwAAgIgAQYUfAIAACwAAAAQHAAAAS0VZX1VQAAQHAAAAR2V0S2V5AAQCAAAAUQADAAAAAAAAAAABAAQCAAAAVwADAAAAAAAA8D8EAgAAAEUAAwAAAAAAAABABAIAAABSAAMAAAAAAAAIQAAAAAADAAAAAAABEQEQEAAAAEBvYmZ1c2NhdGVkLmx1YQA0AAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFYAAABWAAAAVgAAAFYAAABWAAAAVgAAAFYAAABWAAAAVgAAAFYAAABWAAAAVgAAAFYAAABXAAAAVwAAAFcAAABXAAAAVwAAAFcAAABXAAAAVwAAAFcAAABXAAAAVwAAAFcAAABXAAAAWAAAAFgAAABYAAAAWAAAAFgAAABYAAAAWAAAAFgAAABYAAAAWAAAAFgAAABYAAAAWAAAAAIAAAAEAAAAYmJhAAAAAAA0AAAABAAAAGNiYQAAAAAANAAAAAMAAAAFAAAAX0VOVgAEAAAAYWJhAAQAAABfYmEAWQAAAFsAAAABAAIbAAAARgBAAEdAwAAYgMAAF8ABgBjAQAAXgACAQwCAAF8AAAEXAASAQwAAAF8AAAEXQAOARgBAAEdAwAAYAMEAF8ABgBjAQAAXgACAQwCAAF8AAAEXAAGAQwAAAF8AAAEXQACAQwAAAF8AAAEfAIAABQAAAAQHAAAAbXlIZXJvAAQJAAAAY2hhck5hbWUABAQAAABMdXgAAwAAAAAAAPA/BAcAAABWZWlnYXIAAAAAAAEAAAAAABAAAABAb2JmdXNjYXRlZC5sdWEAGwAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFoAAABaAAAAWgAAAFsAAABbAAAAWwAAAFsAAABbAAAAWwAAAFsAAABbAAAAWwAAAFsAAABbAAAAWwAAAFsAAABbAAAAWwAAAAEAAAAEAAAAYmJhAAAAAAAbAAAAAQAAAAUAAABfRU5WAFwAAABmAAAAAQAFUAAAAEYAwABdgIAASQAAAEZAwABHgMAAWwAAABfAEYBHwEAAGADBABcAEYAKgMGCTMBBAF2AAAGFAAAAWABCAReAD4AYQMIAF0ADgIaAQgGbQAAAF4ACgIaAwgGbAAAAF8ABgIzAQgCdQAABhwBDAMAAAAABQQMAnUCAAYiAQ4UXgAuAGMDDABdAA4CGQEMBm0AAABeAAoCGQMMBmwAAABfAAYCMwEIAnUAAAYcAQwDAAAAAAUEDAJ1AgAGIgMOGF4AHgBgAxAAXQAOAhkBCAZtAAAAXgAKAhkDCAZsAAAAXwAGAjMBCAJ1AAAGHAEMAwAAAAAFBAwCdQIABiIDDhBeAA4AYQMQAFwADgIaARAGbQAAAF0ACgIaAxAGbAAAAF4ABgIzAQgCdQAABhwBDAMAAAAABQQMAnUCAAYiAQ4kfAIAAEwAAAAQQAAAAR2V0Q3VzdG9tVGFyZ2V0AAQHAAAAQ29uZmlnAAQEAAAAdG9nAAQHAAAAaGVhZGVyAAMAAAAAACBtQAQEAAAAcG9zAAMAAAAAAAA7QAQIAAAARGVjb2RlMQAAAwAAAAAAAABAAwAAAAAAAAAABAYAAABCbG9jawAEBQAAAHNraXAAAwAAAAAAAPA/AQEDAAAAAAAAa0ADAAAAAABgZkADAAAAAADgbEADAAAAAAAACEAAAAAABAAAAAELAAABEAEREAAAAEBvYmZ1c2NhdGVkLmx1YQBQAAAAXAAAAFwAAABcAAAAXQAAAF0AAABdAAAAXQAAAF4AAABeAAAAXgAAAF4AAABfAAAAXwAAAGAAAABgAAAAYAAAAGEAAABhAAAAYQAAAGEAAABhAAAAYQAAAGEAAABhAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABjAAAAYwAAAGMAAABjAAAAYwAAAGMAAABjAAAAYwAAAGMAAABjAAAAYwAAAGMAAABjAAAAYwAAAGMAAABjAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGUAAABlAAAAZQAAAGUAAABlAAAAZQAAAGUAAABlAAAAZQAAAGUAAABmAAAAZgAAAGYAAABmAAAAZgAAAGYAAAACAAAABAAAAGJiYQAAAAAAUAAAAAQAAABjYmEADQAAAE8AAAAEAAAABAAAAF9hYQAFAAAAX0VOVgAEAAAAX2JhAAQAAABhYmEAZwAAAG4AAAAAAAI2AAAABQAAAAwAQAAdQAABBkDAAAeAQAAbAAAAF0ACgAZAwAAHgEAAB8BAAEYAwQBHwMAAGEAAABeAAIAGQMAAB4BAAB8AAAEGQMAAB0BBABsAAAAXQAeABkDAAAdAQQAHgEEAGwAAABcABoAGQMAAB0BBAAfAQQAbAAAAF8AEgAZAwAAHQEEAB8BBAAcAQgAbAAAAF0ADgAZAwAAHQEEAB8BBAAcAQgAHwEAARgDBAEfAwAAYQAAAFwABgAZAwAAHQEEAB8BBAAcAQgAfAAABBgBCAB8AAAEfAIAACQAAAAQHAAAAdXBkYXRlAAQDAAAAX0cABAsAAABNTUFfVGFyZ2V0AAQFAAAAdHlwZQAEBwAAAG15SGVybwAECgAAAEF1dG9DYXJyeQAECgAAAENyb3NzaGFpcgAEEQAAAEF0dGFja19Dcm9zc2hhaXIABAcAAAB0YXJnZXQAAAAAAAIAAAABDAAAEAAAAEBvYmZ1c2NhdGVkLmx1YQA2AAAAZwAAAGcAAABnAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABsAAAAbAAAAGwAAABsAAAAbQAAAG0AAABtAAAAbQAAAG0AAABtAAAAbQAAAG0AAABtAAAAbQAAAG0AAABtAAAAbQAAAG0AAABtAAAAbQAAAG4AAABuAAAAbgAAAG4AAABuAAAAbgAAAG4AAABuAAAAbgAAAG4AAABuAAAAbgAAAG4AAABuAAAAbgAAAG4AAABuAAAAAAAAAAIAAAAEAAAAYWFhAAUAAABfRU5WAG8AAABxAAAAAwAHGgAAAMYAQADbAAAAFwAEgMZAQADHgMABx8DAAdsAAAAXwAKAxgBBAAFBAQBLQQEASgEAg0pBgINKgQCESkGAhEqBAIXdgIABzMDCAd1AAAEXAAGAxgBDAAABAABAAYAAgAEAAd1AAAIfAIAADQAAAAQJAAAAVklQX1VTRVIABAcAAABDb25maWcABAkAAABwckNvbmZpZwAEAwAAAHBjAAQHAAAAUGFja2V0AAQHAAAAU19DQVNUAAQIAAAAc3BlbGxJZAAEBgAAAGZyb21YAAQGAAAAZnJvbVkABAQAAAB0b1gABAQAAAB0b1kABAUAAABzZW5kAAQKAAAAQ2FzdFNwZWxsAAAAAAABAAAAAAAQAAAAQG9iZnVzY2F0ZWQubHVhABoAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHEAAABxAAAAcQAAAHEAAABxAAAAcQAAAHEAAABxAAAAcQAAAHEAAABxAAAAcQAAAHEAAABxAAAAcQAAAHEAAABxAAAAcQAAAAMAAAAEAAAAYmJhAAAAAAAaAAAABAAAAGNiYQAAAAAAGgAAAAQAAABkYmEAAAAAABoAAAABAAAABQAAAF9FTlYAAQAAAAEAEAAAAEBvYmZ1c2NhdGVkLmx1YQC0AAAAAQAAAAEAAAACAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAAFAAAABgAAAAYAAAAHAAAABwAAAAcAAAAHAAAACAAAAAgAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAoAAAAKAAAACgAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAA0AAAANAAAADQAAAA0AAAANAAAADQAAAA0AAAANAAAADgAAABIAAAASAAAADgAAABIAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAVAAAAFQAAABUAAAAUAAAAFQAAABUAAAAWAAAAFgAAABYAAAAWAAAAGAAAABgAAAAYAAAAGAAAABkAAAAZAAAAGQAAABgAAAAZAAAAGQAAABkAAAAZAAAAGgAAABkAAAAZAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGwAAABsAAAAbAAAAGwAAABsAAAAbAAAAGwAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAAB0AAAAdAAAAHQAAAB0AAAAdAAAAHQAAAB0AAAAdAAAAHgAAAB4AAAAeAAAAHgAAAB4AAAAeAAAAMgAAAB8AAABSAAAAMwAAAFgAAABTAAAAWwAAAFkAAABmAAAAXAAAAG4AAABnAAAAcQAAAG8AAABxAAAAEwAAAAMAAABkYwABAAAAtAAAAAMAAABfZAACAAAAtAAAAAMAAABhZAAKAAAAtAAAAAMAAABiZAANAAAAtAAAAAMAAABjZAARAAAAtAAAAAMAAABkZAASAAAAtAAAAAQAAABiYmEAGAAAAEgAAAAEAAAAX19hAIcAAAC0AAAABAAAAGFfYQCIAAAAtAAAAAQAAABiX2EAiAAAALQAAAAEAAAAY19hAIgAAAC0AAAABAAAAGRfYQCIAAAAtAAAAAQAAABfYWEAiAAAALQAAAAEAAAAYWFhAI4AAAC0AAAABAAAAGJhYQCXAAAAtAAAAAQAAABjYWEAmAAAALQAAAAEAAAAZGFhAJkAAAC0AAAABAAAAF9iYQCfAAAAtAAAAAQAAABhYmEApQAAALQAAAABAAAABQAAAF9FTlYA"), nil, "bt", _ENV))()